### ISSUE TITLE
how add disable_notification?

### ISSUE THREAD

**Issue by paul8909** [GeorgiyDemo/InstagramToTelegram#1]
im try add in bot.sendPhoto... disable_notification = true, but it not work

**Comment by GeorgiyDemo** [comment]
> im try add in bot.sendPhoto... disable_notification = true, but it not work

Hey, this search can help you:
https://github.com/python-telegram-bot/python-telegram-bot/search?q=disable_notification&unscoped_q=disable_notification

bot.send_message with disable_notification example:
https://github.com/python-telegram-bot/python-telegram-bot/blob/79448056278058a6d7149031d5e530f2a3f2ae8f/tests/test_bot.py

Maybe you want to use bot.send_photo instead of bot.sendPhoto or something like that?

**Comment by paul8909** [comment]
I try it:
bot.sendPhoto(chat_id=channel_name, photo=media_json["thumbnail_src"], caption="By @"+username+"\n"+media_text, disable_notification = true)

bot.sendPhoto(chat_id=channel_name, photo=media_json["thumbnail_src"], caption="By @"+username+"\n"+media_text, disable_notification = false)

bot.sendPhoto(chat_id=channel_name, photo=media_json["thumbnail_src"], caption="By @"+username+"\n"+media_text, disable_notification = disable_notification)

bot.sendPhoto(chat_id=channel_name, photo=media_json["thumbnail_src"], caption="By @"+username+"\n"+media_text, disable_notification = None)

bot.sendPhoto(chat_id=channel_name, photo=media_json["thumbnail_src"], caption="By @"+username+"\n"+media_text, disable_notification = "true")

But it all not work, i cant understand, why?
